//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMDT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceDetails
    {
        public int invoiceID { get; set; }
        public int ingID { get; set; }
        public double quatity { get; set; }
        public decimal price { get; set; }
    

        public virtual Invoice Invoice { get; set; }
        public virtual Ingredient Ingredient { get; set; }

    }
}
