//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMDT.Models
{
    using System;
    using System.Collections.Generic;
    public interface KhuyenMaiPrototype
    {
        KhuyenMaiPrototype clone();
    }
    public partial class KhuyenMai : KhuyenMaiPrototype
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KhuyenMai()
        {
            this.Order = new HashSet<Order>();
        }
    
        public int ID { get; set; }
        public string TenQuanLy { get; set; }
        public string TenHienThi { get; set; }
        public string MaKhuyenMai { get; set; }
        public string LoaiKhuyenMai { get; set; }
        public Nullable<decimal> GiaTriKhuyenMai { get; set; }
        public Nullable<decimal> GiaTriGiamToiDa { get; set; }
        public Nullable<decimal> SoTienGiam { get; set; }
        public Nullable<decimal> DieuKienApDung_DonHangToiThieu { get; set; }
        public Nullable<int> DieuKienApDung_SoLuongToiThieu { get; set; }
        public Nullable<System.DateTime> ThoiGianBatDau { get; set; }
        public Nullable<System.DateTime> ThoiGianKetThuc { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Order { get; set; }

        public KhuyenMaiPrototype clone()
        {
            KhuyenMai khuyenMai = new KhuyenMai();
            khuyenMai.TenQuanLy = TenQuanLy;
            khuyenMai.TenHienThi = TenHienThi;
            khuyenMai.MaKhuyenMai = MaKhuyenMai;
            khuyenMai.LoaiKhuyenMai = LoaiKhuyenMai;
            khuyenMai.GiaTriKhuyenMai = GiaTriKhuyenMai;
            khuyenMai.GiaTriGiamToiDa = GiaTriGiamToiDa;
            khuyenMai.SoTienGiam = SoTienGiam;
            khuyenMai.DieuKienApDung_DonHangToiThieu = DieuKienApDung_DonHangToiThieu;
            khuyenMai.DieuKienApDung_SoLuongToiThieu = DieuKienApDung_SoLuongToiThieu;
            return khuyenMai;
        }
    }
}
