//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMDT.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public int addressID { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string numberPhone { get; set; }
        public string address1 { get; set; }
        public bool priority { get; set; }
        public string note { get; set; }
        public string userID { get; set; }
    
        public virtual User User { get; set; }
    }
}
